In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
data=pd.read_csv('Social_Network_Ads.csv')
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
data.shape

(400, 5)

In [ ]:
data.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
data=pd.get_dummies(data)

In [ ]:
data.head()

User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0  15624510   19            19000          0              0            1
1  15810944   35            20000          0              0            1
2  15668575   26            43000          0              1            0
3  15603246   27            57000          0              1            0
4  15804002   19            76000          0              0            1

In [ ]:
data.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Female',
       'Gender_Male'],
      dtype='object')

In [ ]:
x=data.drop(['User ID','Purchased'],axis=1)
y=data['Purchased']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
#### SVM

In [ ]:
from sklearn.svm import SVC

In [ ]:
svm_cls=SVC(kernel='linear')
svm_cls=svm_cls.fit(x_train,y_train)
y_pred_svm=svm_cls.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
confusion_matrix(y_test,y_pred_svm)

array([[48,  4],
       [ 9, 19]])

In [ ]:
accuracy_score(y_test,y_pred_svm)

0.8375

In [ ]:
svm_cls1=SVC(kernel='rbf')
svm_cls1=svm_cls1.fit(x_train,y_train)
y_pred_svm1=svm_cls1.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred_svm1)

array([[49,  3],
       [18, 10]])

In [ ]:
accuracy_score(y_test,y_pred_svm1)

0.7375

In [ ]:
## Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dt_cls=DecisionTreeClassifier()
model=dt_cls.fit(x_train,y_train)
y_pred_dt=model.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred_dt)

array([[45,  7],
       [ 7, 21]])

In [ ]:
accuracy_score(y_test,y_pred_dt)

0.825

In [ ]:
### Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf_cls=RandomForestClassifier()
model_rf=rf_cls.fit(x_train,y_train)
y_pred_rf=model_rf.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred_rf)

array([[47,  5],
       [ 3, 25]])

In [ ]:
accuracy_score(y_test,y_pred_rf)

0.9

In [ ]:
rf_cls=RandomForestClassifier(n_estimators=12,random_state=42)
model_rf=rf_cls.fit(x_train,y_train)
y_pred_rf=model_rf.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred_rf)

array([[48,  4],
       [ 4, 24]])

In [ ]:
accuracy_score(y_test,y_pred_rf)

0.9