In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(4,)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(2, 4)

In [ ]:
arr3=([[[1,2,3],[5,6,7]],[[8,9,10],[11,12,13]],[[17,18,19],[20,21,22]]])
arr3

[[[1, 2, 3], [5, 6, 7]],
 [[8, 9, 10], [11, 12, 13]],
 [[17, 18, 19], [20, 21, 22]]]

In [ ]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr3=np.arange(4,20)
print(arr3)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
arr3.shape

(16,)

In [ ]:
arr3.reshape(4,4)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arr3.reshape(2,8)

array([[ 4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
arr3.reshape(2,4,2)

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [ ]:
### array slicing
arr=np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[4]

4

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr[[2,4,6]]

array([2, 4, 6])

In [ ]:
arr=np.array([4,1,9,3,7,3,2])

In [ ]:
arr[[2,4,6]]

array([9, 7, 2])

In [ ]:
arr2=np.array([[1,2,-9,8],[5,7,-3,-8],[12,14,-88,45]])

In [ ]:
arr2

array([[  1,   2,  -9,   8],
       [  5,   7,  -3,  -8],
       [ 12,  14, -88,  45]])

In [ ]:
arr2[2]

array([ 12,  14, -88,  45])

In [ ]:
arr2[:,1]

array([ 2,  7, 14])

In [ ]:
arr2[[1,2]]

array([[  5,   7,  -3,  -8],
       [ 12,  14, -88,  45]])

In [ ]:
arr2[[1,2],[2]]

array([ -3, -88])

In [ ]:
arr3=np.arange(10,82,2)
arr3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [ ]:
len(arr3)

36

In [ ]:
arr3=np.arange(10,82,2).reshape(6,6)
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [ ]:
arr3[:,[0,3]]         ### all rows, 0th and 3rd column

array([[10, 16],
       [22, 28],
       [34, 40],
       [46, 52],
       [58, 64],
       [70, 76]])

In [ ]:
arr3[:2,:]      ## row=2 column=all

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

In [ ]:
### numerical operations

In [ ]:
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [ ]:
arr3.sum()

1620

In [ ]:
arr3.mean()

45.0

In [ ]:
arr3.mean(0)

array([40., 42., 44., 46., 48., 50.])

In [ ]:
arr3.mean(1)

array([15., 27., 39., 51., 63., 75.])

In [ ]:
arr = np.arange(1,17).reshape(4,4)

In [ ]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr+5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
arr*5

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60],
       [65, 70, 75, 80]])

In [ ]:
arr[3]

array([13, 14, 15, 16])

In [ ]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr[2]=-9

In [ ]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [-9, -9, -9, -9],
       [13, 14, 15, 16]])

In [ ]:
np.sqrt(arr)

<ipython-input-57-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [       nan,        nan,        nan,        nan],
       [3.60555128, 3.74165739, 3.87298335, 4.        ]])

In [ ]:
### special arrays
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
A = np.arange(8).reshape(2,4)
B =np.arange(8).reshape(2,4)
print(A)

[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
A.dot(B)

ValueError: ignored

In [ ]:
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
A.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [ ]:
### stacking of arrays

a=np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b=np.ones((4,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#### vertical stacking /concatenation
np.vstack((a,b))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
### horizontal stacking
np.hstack((a,b))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.concatenate([a,b])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.concatenate([a,b],axis=1)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
### flatten
a.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
## random numbers
np.random.rand(5)

array([0.56800622, 0.77964271, 0.59958766, 0.86656886, 0.95316032])

In [ ]:
np.random.randint(5)

3

In [ ]:
np.random.randint(5,20)

10

In [ ]:
np.random.randint(0,50,6)

array([21, 15, 12, 48, 22, 46])

In [ ]:
arr =np.random.randint(0,50,6)
arr

array([30, 45,  8,  0, 24, 49])

In [ ]:
arr =np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [ ]:
np.random.shuffle(arr)
arr

array([1, 3, 2, 4, 5])